"""Second Migration

Revision ID: 76f120bed54e
Revises: 55daa6e81c8d
Create Date: 2022-10-28 14:47:50.573216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f120bed54e'
down_revision = '55daa6e81c8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
