"""New Migration

Revision ID: e44ec5867e9e
Revises: 76f120bed54e
Create Date: 2022-10-28 22:23:01.443694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44ec5867e9e'
down_revision = '76f120bed54e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_fullname_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_fullname_key', 'users', ['fullname'])
    # ### end Alembic commands ###
